

SUCCESS = "/SUCCESS"
NEW = "/NEW"
UPDATE = "/UPDATE"
FAIL = "/FAIL"
DELETE = "/DELETE"
STATUS = "/STATUS"

SETTINGS = "SETTINGS"
ITEM = "MEDIA_ITEM"
LIST = "MEDIA_LIST"
QUEUE = "QUEUE"
VOTE = "VOTE"
PLAYING = "PLAYING"
SPOTIFY_SERVICE = "SPOTIFY_SERVICE"
AUTHORIZED = "/AUTHORIZED"
CLIENT = "CLIENT"
CONFIG = "CONFIG"
